platform :ios, '8.0'

target "living" do
pod 'AFNetworking',             '~> 1.3.4'
pod 'MBProgressHUD'
pod 'UIImage-Helpers',          '~> 0.0.2'
pod 'SDWebImage',               '~> 3.8'

pod 'HMSegmentedControl'
pod 'ZYQAssetPickerController'
pod 'MIHCrypto', 		'~> 0.4.0'
end
