platform :ios, '8.0'

target "living" do
pod 'AFNetworking',             '~> 1.3.4'
pod 'MBProgressHUD'
pod 'UIImage-Helpers',          '~> 0.0.2'
pod 'SDWebImage',               '~> 3.8'

pod 'HMSegmentedControl'
pod 'ZYQAssetPickerController'
pod 'MIHCrypto', 		'~> 0.4.0'
pod 'WebsocketStompKit', :git => 'https://github.com/rguldener/WebsocketStompKit.git'
pod 'jetfire', '0.1.2'
pod 'Masonry','1.0.1'
pod 'Bugtags'
pod 'FMDB', '~> 2.7.2'
pod 'UMengAnalytics', '~> 4.2.4'



end
